# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  push:
    # Use docker-publisher from above as the Docker container to run this job in
    executor: docker-publisher

    steps:
      # Set up a separate Docker environment to run `docker` commands in
      - setup_remote_docker

      # Load and un-archive the Docker image
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: CI-Cours
          command: docker load --input /tmp/workspace/image.tar

      # Log in to Docker Hub and push the image
      - run:
          name: Publish Docker image
          command: |
            echo "${$DOCKERHUB_PASSWORD}" | docker login --username "nkrattinger" --password-stdin
            docker push "${ci-cours}"

  run-app:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:2022.08
        auth:
          username: nkrattinger
          password: $DOCKERHUB_PASSWORD  # context / project
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --tag ci-cours .
      - run:
          name : "Test access"
          command: |
            docker run -d --name ci-cours -p 8080:8080 ci-cours
            docker run --network container:ci-cours appropriate/curl --retry 10 --retry-connrefused http://localhost:8080
      - run:  docker push ci-cours:latest

      - push:
          # Build needs to finish first
          requires:
            - build
          # Only push images from the main branch
          filters:
            branches:
              only: main

workflows:
  run-workflow:
    jobs:
      - run-app
      - push
